INFO:2025-04-28 13:30:29,065:MainThread:Dhan.py  started system
INFO:2025-04-28 13:30:29,065:MainThread:STARTED THE PROGRAM
INFO:2025-04-28 13:30:35,135:MainThread:Alert sent via bot to chat ID: 7783423452
INFO:2025-04-28 13:30:36,532:MainThread:Alert sent via bot to chat ID: 6320586394
INFO:2025-04-28 13:30:36,533:MainThread:Starting full scan at 13:30:36
INFO:2025-04-28 13:30:36,533:MainThread:Processing batch 1/11 (10 stocks)...
ERROR:2025-04-28 13:30:38,633:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:38,644:MainThread:Not enough daily data for ABB
ERROR:2025-04-28 13:30:41,752:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:41,760:MainThread:Not enough daily data for AUBANK
ERROR:2025-04-28 13:30:44,874:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:44,884:MainThread:Not enough daily data for AARTIIND
ERROR:2025-04-28 13:30:47,977:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:47,989:MainThread:Not enough daily data for ADANIENT
ERROR:2025-04-28 13:30:51,098:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:51,106:MainThread:Not enough daily data for ADANIGREEN
ERROR:2025-04-28 13:30:54,212:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:54,220:MainThread:Not enough daily data for ADANIPORTS
ERROR:2025-04-28 13:30:57,325:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:30:57,333:MainThread:Not enough daily data for AMBUJACEM
ERROR:2025-04-28 13:31:00,415:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:00,424:MainThread:Not enough daily data for ASHOKLEY
ERROR:2025-04-28 13:31:03,516:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:03,524:MainThread:Not enough daily data for ASIANPAINT
ERROR:2025-04-28 13:31:06,614:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:06,624:MainThread:Not enough daily data for AUROPHARMA
INFO:2025-04-28 13:31:12,633:MainThread:Processing batch 2/11 (10 stocks)...
ERROR:2025-04-28 13:31:14,722:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:14,728:MainThread:Not enough daily data for AXISBANK
ERROR:2025-04-28 13:31:17,824:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:17,828:MainThread:Not enough daily data for BSOFT
ERROR:2025-04-28 13:31:20,913:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:20,921:MainThread:Not enough daily data for BSE
ERROR:2025-04-28 13:31:24,030:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:24,040:MainThread:Not enough daily data for BAJAJ-AUTO
ERROR:2025-04-28 13:31:27,129:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:27,140:MainThread:Not enough daily data for BAJFINANCE
ERROR:2025-04-28 13:31:30,248:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:30,257:MainThread:Not enough daily data for BAJAJFINSV
ERROR:2025-04-28 13:31:33,346:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:33,355:MainThread:Not enough daily data for BANDHANBNK
ERROR:2025-04-28 13:31:36,460:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:36,466:MainThread:Not enough daily data for BANKBARODA
ERROR:2025-04-28 13:31:39,570:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:39,578:MainThread:Not enough daily data for BEL
ERROR:2025-04-28 13:31:42,668:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:42,676:MainThread:Not enough daily data for BHARATFORG
INFO:2025-04-28 13:31:48,682:MainThread:Processing batch 3/11 (10 stocks)...
ERROR:2025-04-28 13:31:50,791:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:50,802:MainThread:Not enough daily data for BHEL
ERROR:2025-04-28 13:31:53,909:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:53,920:MainThread:Not enough daily data for BPCL
ERROR:2025-04-28 13:31:57,021:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
WARNING:2025-04-28 13:31:57,032:MainThread:Not enough daily data for BHARTIARTL
INFO:2025-04-28 13:32:06,428:MainThread:Dhan.py  started system
INFO:2025-04-28 13:32:06,428:MainThread:STARTED THE PROGRAM
INFO:2025-04-28 13:32:12,171:MainThread:Alert sent via bot to chat ID: 7783423452
INFO:2025-04-28 13:32:13,297:MainThread:Alert sent via bot to chat ID: 6320586394
INFO:2025-04-28 13:32:13,297:MainThread:Starting full scan at 13:32:13
INFO:2025-04-28 13:32:13,298:MainThread:Processing batch 1/11 (10 stocks)...
DEBUG:2025-04-28 13:32:17,527:MainThread:Intraday data for ABB - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:32:17,528:MainThread:Intraday data for ABB - first row: {'open': 5720.0, 'high': 5733.0, 'low': 5672.0, 'close': 5676.0, 'volume': 27483.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:32:20,604:MainThread:LTP fetch successful for ABB: 5525
DEBUG:2025-04-28 13:32:25,844:MainThread:Intraday data for AUBANK - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:32:25,844:MainThread:Intraday data for AUBANK - first row: {'open': 658.5, 'high': 671.7, 'low': 655.6, 'close': 669.5, 'volume': 890446.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:32:28,917:MainThread:LTP fetch successful for AUBANK: 680
INFO:2025-04-28 13:32:35,150:MainThread:Dhan.py  started system
INFO:2025-04-28 13:32:35,150:MainThread:STARTED THE PROGRAM
INFO:2025-04-28 13:32:40,288:MainThread:Alert sent via bot to chat ID: 7783423452
INFO:2025-04-28 13:32:41,467:MainThread:Alert sent via bot to chat ID: 6320586394
INFO:2025-04-28 13:32:41,469:MainThread:Starting full scan at 13:32:41
INFO:2025-04-28 13:32:41,469:MainThread:Processing batch 1/1 (5 stocks)...
DEBUG:2025-04-28 13:32:45,729:MainThread:Intraday data for ABB - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:32:45,729:MainThread:Intraday data for ABB - first row: {'open': 5720.0, 'high': 5733.0, 'low': 5672.0, 'close': 5676.0, 'volume': 27483.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:32:48,805:MainThread:LTP fetch successful for ABB: 5526.5
DEBUG:2025-04-28 13:32:54,054:MainThread:Intraday data for AUBANK - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:32:54,054:MainThread:Intraday data for AUBANK - first row: {'open': 658.5, 'high': 671.7, 'low': 655.6, 'close': 669.5, 'volume': 890446.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:32:57,133:MainThread:LTP fetch successful for AUBANK: 679.95
DEBUG:2025-04-28 13:33:02,396:MainThread:Intraday data for AARTIIND - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:33:02,398:MainThread:Intraday data for AARTIIND - first row: {'open': 435.0, 'high': 442.45, 'low': 433.8, 'close': 442.0, 'volume': 280641.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:33:05,478:MainThread:LTP fetch successful for AARTIIND: 431
DEBUG:2025-04-28 13:33:10,742:MainThread:Intraday data for ADANIENT - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:33:10,742:MainThread:Intraday data for ADANIENT - first row: {'open': 2450.0, 'high': 2459.9, 'low': 2441.0, 'close': 2448.3, 'volume': 67783.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:33:13,813:MainThread:LTP fetch successful for ADANIENT: 2376.9
INFO:2025-04-28 13:33:13,813:MainThread:Added ADANIENT to hot watchlist
INFO:2025-04-28 13:33:14,958:MainThread:Alert sent via bot to chat ID: 7783423452
INFO:2025-04-28 13:33:16,125:MainThread:Alert sent via bot to chat ID: 6320586394
INFO:2025-04-28 13:33:16,126:MainThread:INSIDE VALUE | ADANIENT | Median: 2379.1 | Threshold: 2402.891
DEBUG:2025-04-28 13:33:21,386:MainThread:Intraday data for ADANIGREEN - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:33:21,387:MainThread:Intraday data for ADANIGREEN - first row: {'open': 956.9, 'high': 962.65, 'low': 954.05, 'close': 955.2, 'volume': 374628.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:33:24,448:MainThread:LTP fetch successful for ADANIGREEN: 936.5
INFO:2025-04-28 13:33:24,448:MainThread:Added ADANIGREEN to hot watchlist
INFO:2025-04-28 13:33:25,609:MainThread:Alert sent via bot to chat ID: 7783423452
INFO:2025-04-28 13:33:26,743:MainThread:Alert sent via bot to chat ID: 6320586394
INFO:2025-04-28 13:33:26,744:MainThread:INSIDE VALUE | ADANIGREEN | Median: 930.7000000000002 | Threshold: 940.0070000000002
INFO:2025-04-28 13:33:33,765:MainThread:Scanning hot list at 13:33:33 - 2 stocks
DEBUG:2025-04-28 13:33:36,838:MainThread:LTP fetch successful for ADANIENT: 2377.2
DEBUG:2025-04-28 13:33:41,102:MainThread:Intraday data for ADANIENT - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:33:41,103:MainThread:Intraday data for ADANIENT - first row: {'open': 2450.0, 'high': 2459.9, 'low': 2441.0, 'close': 2448.3, 'volume': 67783.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:33:44,177:MainThread:LTP fetch successful for ADANIENT: 2376.3
DEBUG:2025-04-28 13:33:48,259:MainThread:LTP fetch successful for ADANIGREEN: 936.15
DEBUG:2025-04-28 13:33:52,509:MainThread:Intraday data for ADANIGREEN - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:33:52,510:MainThread:Intraday data for ADANIGREEN - first row: {'open': 956.9, 'high': 962.65, 'low': 954.05, 'close': 955.2, 'volume': 374628.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:33:55,592:MainThread:LTP fetch successful for ADANIGREEN: 936.15
INFO:2025-04-28 13:34:34,765:MainThread:Scanning hot list at 13:34:34 - 2 stocks
DEBUG:2025-04-28 13:34:37,851:MainThread:LTP fetch successful for ADANIENT: 2377.7
DEBUG:2025-04-28 13:34:42,079:MainThread:Intraday data for ADANIENT - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:34:42,081:MainThread:Intraday data for ADANIENT - first row: {'open': 2450.0, 'high': 2459.9, 'low': 2441.0, 'close': 2448.3, 'volume': 67783.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:34:45,169:MainThread:LTP fetch successful for ADANIENT: 2378.2
DEBUG:2025-04-28 13:34:49,249:MainThread:LTP fetch successful for ADANIGREEN: 936.5
DEBUG:2025-04-28 13:34:53,498:MainThread:Intraday data for ADANIGREEN - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:34:53,498:MainThread:Intraday data for ADANIGREEN - first row: {'open': 956.9, 'high': 962.65, 'low': 954.05, 'close': 955.2, 'volume': 374628.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:34:56,572:MainThread:LTP fetch successful for ADANIGREEN: 936.8
INFO:2025-04-28 13:35:35,726:MainThread:Scanning hot list at 13:35:35 - 2 stocks
DEBUG:2025-04-28 13:35:38,807:MainThread:LTP fetch successful for ADANIENT: 2376.6
DEBUG:2025-04-28 13:35:43,055:MainThread:Intraday data for ADANIENT - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:35:43,056:MainThread:Intraday data for ADANIENT - first row: {'open': 2450.0, 'high': 2459.9, 'low': 2441.0, 'close': 2448.3, 'volume': 67783.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:35:46,127:MainThread:LTP fetch successful for ADANIENT: 2376.6
DEBUG:2025-04-28 13:35:50,192:MainThread:LTP fetch successful for ADANIGREEN: 936
DEBUG:2025-04-28 13:35:54,429:MainThread:Intraday data for ADANIGREEN - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:35:54,430:MainThread:Intraday data for ADANIGREEN - first row: {'open': 956.9, 'high': 962.65, 'low': 954.05, 'close': 955.2, 'volume': 374628.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:35:57,507:MainThread:LTP fetch successful for ADANIGREEN: 936.1
INFO:2025-04-28 13:36:36,657:MainThread:Scanning hot list at 13:36:36 - 2 stocks
DEBUG:2025-04-28 13:36:39,727:MainThread:LTP fetch successful for ADANIENT: 2377.8
DEBUG:2025-04-28 13:36:43,934:MainThread:Intraday data for ADANIENT - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:36:43,934:MainThread:Intraday data for ADANIENT - first row: {'open': 2450.0, 'high': 2459.9, 'low': 2441.0, 'close': 2448.3, 'volume': 67783.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:36:46,994:MainThread:LTP fetch successful for ADANIENT: 2378.9
DEBUG:2025-04-28 13:36:51,057:MainThread:LTP fetch successful for ADANIGREEN: 936.75
DEBUG:2025-04-28 13:36:55,265:MainThread:Intraday data for ADANIGREEN - columns: ['open', 'high', 'low', 'close', 'volume', 'timestamp']
DEBUG:2025-04-28 13:36:55,266:MainThread:Intraday data for ADANIGREEN - first row: {'open': 956.9, 'high': 962.65, 'low': 954.05, 'close': 955.2, 'volume': 374628.0, 'timestamp': Timestamp('2025-04-24 09:15:00+0530', tz='UTC+05:30')}
DEBUG:2025-04-28 13:36:58,320:MainThread:LTP fetch successful for ADANIGREEN: 937.4
INFO:2025-04-28 13:37:35,344:MainThread:Dhan.py  started system
INFO:2025-04-28 13:37:35,345:MainThread:STARTED THE PROGRAM
ERROR:2025-04-28 13:37:40,464:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:42,569:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:44,671:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:46,763:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:46,802:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 432, in get_historical_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-04-28 13:37:48,888:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:48,938:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 432, in get_historical_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-04-28 13:37:51,020:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
ERROR:2025-04-28 13:37:53,118:MainThread:Exception in Getting OHLC data as {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 464, in get_historical_data
    raise Exception(ohlc)
Exception: {'status': 'failure', 'remarks': {'error_code': 'DH-901', 'error_type': 'Invalid_Authentication', 'error_message': 'Client ID or user generated access token is invalid or expired.'}, 'data': {'errorType': 'Invalid_Authentication', 'errorCode': 'DH-901', 'errorMessage': 'Client ID or user generated access token is invalid or expired.'}}
INFO:2025-04-28 13:38:25,928:MainThread:Dhan.py  started system
INFO:2025-04-28 13:38:25,928:MainThread:STARTED THE PROGRAM
ERROR:2025-04-28 13:38:53,457:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 432, in get_historical_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
ERROR:2025-04-28 13:38:58,727:MainThread:Exception in Getting OHLC data as Check the Tradingsymbol or Exchange
Traceback (most recent call last):
  File "/Users/mayankthole/Desktop/dhan-trade/.venv/lib/python3.13/site-packages/Dhan_Tradehull/Dhan_Tradehull.py", line 432, in get_historical_data
    raise Exception("Check the Tradingsymbol or Exchange")
Exception: Check the Tradingsymbol or Exchange
